LibraryManagmentSystemMVC.Web/Controllers/AuthorController.cs
using AutoMapper;
using LibraryManagmentSystemMVC.Application.Interfaces;
using LibraryManagmentSystemMVC.Application.ViewModel.AuthorVm;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LibraryManagmentSystemMVC.Web.Controllers
{
    [Authorize]
    public class AuthorController : Controller
    {
        private readonly IBookService _bookService;

        public AuthorController(IBookService bookService)
        {
            _bookService = bookService;
        }
        public IActionResult Index()
        {
            var model = _bookService.GetAllActiveAuthors();
            return View(model);
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            var author = _bookService.GetAuthorDetail(id);
            return View(author);
        }
        [HttpGet]
        public IActionResult EditAuthor(int id)
        {
            var author = _bookService.GetAuthorForEdit(id);
            return View(author);
        }

        [HttpPost]
        public IActionResult EditAuthor(NewAuthorVm authorVm)
        {
            if(ModelState.IsValid)
            {
                _bookService.UpdateAuthor(authorVm);
                return RedirectToAction("Index");
            }
            return View(authorVm);
        }
        [HttpGet]
        public IActionResult AddAuthor()
        {
            return View(new NewAuthorVm());
        }
        [HttpPost]
        public IActionResult AddAuthor(NewAuthorVm model)
        {
            if(ModelState.IsValid)
            {
                var id = _bookService.AddAuthor(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public IActionResult DeleteAuthor(NewAuthorVm model)
        {
            _bookService.DeleteAuthor(model);
            return RedirectToAction("Index");
        }
    }
}

LibraryManagmentSystemMVC.Web/Controllers/BookController.cs
using LibraryManagmentSystemMVC.Application.Interfaces;
using LibraryManagmentSystemMVC.Application.ViewModel.BookVm;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LibraryManagmentSystemMVC.Web.Controllers
{
    [Authorize]
    public class BookController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IBookService _bookService;
        public BookController(IBookService bookService,ILogger<HomeController> logger)
        {
            _bookService = bookService;
            _logger = logger;
        }
        public IActionResult Index()
        {
            var model = _bookService.GetAllActiveBooksForList();
            return View(model);
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            var book = _bookService.BookDetails(id);
            return View(book);
        }
        [HttpGet]
        public IActionResult CreateBook()
        {
            ViewBag.authorsList = _bookService.GetAllActiveAuthors();
            ViewBag.genreList = _bookService.GetActiveGenres();
            return View(new NewBookVm());
        }
        [HttpPost]
        public IActionResult CreateBook(NewBookVm newBookVm)
        {
            if(ModelState.IsValid)
            {
                _bookService.AddBook(newBookVm);
                return RedirectToAction("Index");
            }
            else
            {     
                return View(newBookVm);
            }
        }

        public IActionResult DeleteBook(NewBookVm newBookVm)
        {
            _bookService.DeleteBook(newBookVm);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditBook(int id)
        {
            var book = _bookService.GetBookToEdit(id);
            ViewBag.authorsList = _bookService.GetAllActiveAuthors();
            ViewBag.genreList = _bookService.GetActiveGenres();
            return View(book);
        }
        [HttpPost]
        public IActionResult EditBook(NewBookVm newBookVm)
        {
            if(ModelState.IsValid)
            {
                _bookService.EditBook(newBookVm);
                return RedirectToAction("Index");
            }
            else
            {
                return View(newBookVm);
            }
        }
    }
}

LibraryManagmentSystemMVC.Web/Controllers/GenreController.cs
using LibraryManagmentSystemMVC.Application.Interfaces;
using LibraryManagmentSystemMVC.Application.ViewModel.GenreVm;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LibraryManagmentSystemMVC.Web.Controllers
{   
    [Authorize]
    public class GenreController : Controller
    {
        private readonly IBookService _bookService;
        public GenreController(IBookService bookService)
        {
            _bookService = bookService;
        }
        public IActionResult Index()
        {
            var model = _bookService.GetActiveGenres();
            return View(model);
        }
        [HttpGet]
        public IActionResult EditGenre(int id)
        {
            var model = _bookService.GetGenreForUpdate(id);
            return View(model);
        }
        [HttpPost]
        public IActionResult EditGenre(NewGenreVm newGenreVm)
        {
            if(ModelState.IsValid)
            {
                _bookService.UpdateGenre(newGenreVm);
                return RedirectToAction("Index");
            }
            return View(newGenreVm);
        }
        [HttpGet]
        public IActionResult CreateGenre()
        {
            return View(new NewGenreVm());
        }
        [HttpPost]
        public IActionResult CreateGenre(NewGenreVm newGenreVm)
        {
            if(ModelState.IsValid)
            {
                _bookService.AddGenre(newGenreVm);
                return RedirectToAction("Index");
            }
            return View(newGenreVm);
        }
        public IActionResult DeleteGenre(NewGenreVm newGenreVm)
        {
            if(ModelState.IsValid)
            {
                _bookService.DeleteGenre(newGenreVm);
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

    }
}

LibraryManagmentSystemMVC.Web/Controllers/UserController.cs
using LibraryManagmentSystemMVC.Application.Interfaces;
using LibraryManagmentSystemMVC.Application.ViewModel.UsersVm;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LibraryManagmentSystemMVC.Web.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class UserController : Controller
    {
        private readonly IUserService _userService;

        public UserController(IUserService userService)
        {
            _userService = userService;
        }

        public IActionResult Index()
        {
            var model = _userService.GetUsers();
            return View(model);
        }
        [HttpGet]
        public IActionResult CreateUser()
        {
            return View(new NewUserVm());
        }
        [HttpPost]
        public async Task<IActionResult> CreateUser(NewUserVm newUserVm)
        {
            if(ModelState.IsValid)
            {     
                var result = await _userService.AddUser(newUserVm);
                return RedirectToAction("Index");
            }
            else
            {
                return  View(newUserVm);
            }   
        }
        public IActionResult RolesList()
        {
            var model = _userService.GetRoles();
            return View(model);
        }
        [HttpGet]
        public IActionResult CreateRole()
        {
            return View(new NewRoleVm());
        }
        [HttpPost]
        public async Task<IActionResult> CreateRole(NewRoleVm newRoleVm)
        {
            if(ModelState.IsValid)
            { 
                await _userService.AddRole(newRoleVm);
                return RedirectToAction("RolesList");
            }
            else
            {
                return View(newRoleVm);
            }

        }
        [HttpGet]
        public IActionResult ChangeRoles(string id)
        {
            var model = _userService.GetUserById(id);
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> ChangeRoles(NewUserVm newUserVm)
        {
            await _userService.ChangeUserRoles(newUserVm.Id, newUserVm.UserRoles);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult UserDetails(string id)
        {
            var model = _userService.GetUserById(id);
            return View(model);
        }
        [HttpGet]
        public IActionResult EditUser(string id)
        {
            var model = _userService.GetUserById(id);
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> EditUser(NewUserVm newUserVm)
        {
            await _userService.EditUser(newUserVm);
            return RedirectToAction("Index");
        }
       [HttpGet]
       public IActionResult ResetPassword(string id)
        {
            var model = _userService.GetUserById(id);
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> ResetPassword(NewUserVm newUserVm)
        {
            await _userService.ResetPassword(newUserVm);
            return RedirectToAction("Index");
        }
    }
}

LibraryManagmentSystemMVC.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LibraryManagmentSystemMVC.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.css">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="wrapper">
        <!-- Sidebar  -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <h4>LMS</h4>
            </div>

            <ul class="list-unstyled components">
                <li>
                    <a href="#reservationSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Rezerwacje</a>
                    <ul class="collapse list-unstyled" id="reservationSubmenu">
                        <li>
                            <a asp-area="" asp-controller="Reservation" asp-action="Index">Aktywne rezerwacje</a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Reservation" asp-action="CompletedReservations">Zakończone rezerwacje</a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Reservation" asp-action="CanceledReservations">Anulowane rezerwacje</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a asp-area="" asp-controller="Book" asp-action="Index">Książki</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Author" asp-action="Index">Autorzy</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Genre" asp-action="Index">Gatunki</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Customer" asp-action="Index">Klienci</a>
                </li>
                @if(User.IsInRole("Administrator") || User.IsInRole("Kierownik"))
                { 
                    <li>
                        <a asp-area="" asp-controller="Document" asp-action="Index">Dokumenty</a>
                    </li>
                }
                @if(User.IsInRole("Administrator"))
                { 
                    <li>
                        <a href="#userSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Administracja</a>
                        <ul class="collapse list-unstyled" id="userSubmenu">
                            <li>
                                <a asp-area="" asp-controller="User" asp-action="Index">Użytkownicy</a>
                            </li>
                            <li>
                                <a asp-area="" asp-controller="User" asp-action="RolesList">Role</a>
                            </li>
                        </ul>
                    </li>
                }
            </ul>

        </nav>

        <!-- Page Content  -->
        <div id="content">
            <div class="container-fluid">
                    <button type="button" id="sidebarCollapse" class="btn btn-info">
                        <i class="bi bi-list"></i>
                    </button>
                <div class="float-right">
                    <partial name="_LoginPartial" />
                </div>
            </div>

            <div class="container">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - LibraryManagmentSystemMVC.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>